### ISSUE TITLE
Em-dashes become double-quotes

### ISSUE THREAD

**Issue by dag** [waylaidwanderer/FicSave#105]
For example: https://www.fanfiction.net/s/8605391/1/Albus-Potter-and-the-Lunar-Eclipse

> "Better, much better—you see that silver smoke? [...]"

In the MOBI and EPUB this paragraph reads:

> "Better, much better"you see that silver smoke?  [...]"

It's particularly confusing in em-dash-heavy paragraphs, and inside quotes as above, and when the paragraph ends in an em-dash. Here's a fun example involving all three of those:

> "I—I—I'm sorry, I—stupid, wanted to—to—I lost a bet, I had to—to leave the dorms at 5:00 in the morning and not come back for an hour and not get caught—"

:arrow_down: 

> "I"I"I'm sorry, I"stupid, wanted to"to"I lost a bet, I had to"to leave the dorms at 5:00 in the morning and not come back for an hour and not get caught""

Adds another dimension to your reading! ;-)

**Comment by donomique** [comment]
i have the same problem for PDF files from asianfanfics ><

**Comment by waylaidwanderer** [comment]
Hi, this issue should be fixed now. Thanks for the report.

**Comment by dag** [comment]
Fix confirmed—thanks!
