### ISSUE TITLE
Fimfiction URLs considered invalid

### ISSUE THREAD

**Issue by AM0263516** [waylaidwanderer/FicSave#108]
Hey it seems like Fimfiction URLs unforunately keep giving me the "invalid URL" error. What could possibly be the cause?

Story URL: http://www.fimfiction.net/story/301007/the-one-where-discord-gets-all-the-mares

Chapter URL: http://www.fimfiction.net/story/301007/1/the-one-where-discord-gets-all-the-mares/the-chapter-where-ship-hits-the-fan

**Comment by waylaidwanderer** [comment]
The cause is fimfiction.net is not on the list of supported sites.
