### ISSUE TITLE
Fic not downloading from FF.net

### ISSUE THREAD

**Issue by moonwatcher99** [waylaidwanderer/FicSave#114]
I can't get anything to download from Fanfiction.net.  It says the story is loading, then nothing.  I save directly to my computer in MOBI format, I don't use the email.  Also, the bookmarklet won't auto load the URL, I have to copy and paste.  (Which I don't mind doing, but I thought it was supposed to be automatic?)

**Comment by jdhiggs** [comment]
I am having the same issue when trying to save a PDF, either directly to my computer or emailing it to myself.  I get no indication of anything happening once I press the 'Download' button.

**Comment by waylaidwanderer** [comment]
This has been fixed for now. @moonwatcher99 it should also resolve the bookmarklet issue.
