### ISSUE TITLE
Unable to download 

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#115]
Can't use ficsave to download any stories from ff.net. Either it failed to build the ebook, seem to start downloading chapter before it blinked away, or the end result is unreadable. The site, as of this writing, is still accessible however.

**Comment by nate10101** [comment]
I'm also having this issue.

**Comment by zerojouno** [comment]
Unable to download from adultfanfiction.org.

**Comment by loganrollo** [comment]
After typing in the URL and telling it to download, the screen blinks and the URL disappears. Nothing else happens.

**Comment by waylaidwanderer** [comment]
Hi everyone, it should be all good now. Thanks for reporting it. Looks like the cleanup script ran out of memory due to PDF generations. I'm still looking into alternatives.
