### ISSUE TITLE
Adult-fanfiction won't download + Request for HTML format

### ISSUE THREAD

**Issue by r778** [waylaidwanderer/FicSave#121]
adultfanfiction downloading has been broken for quite a while, says invalid URL.

There's no working downloader for stories there currently, so would appreciate a fix.

Also is there any chance of HTML support? I've always preferred it and if you had a working clickable index like FLAGfic used to it would be sooooooo much more convenient than any of the other fic savers.

**Comment by sirius16** [comment]
Yeah, I brought this issue up about 23 days ago and they still have yet to respond

**Comment by waylaidwanderer** [comment]
Sorry @sirius16, I'm very busy as of late. Working on my hobbies unfortunately takes a backseat to working for money to pay off a mortgage every month. I'll fix it when I have time.

**Comment by sirius16** [comment]
Ah, yes, sorry to have bothered you then. I had presumed you forgot.

**Comment by waylaidwanderer** [comment]
This has been fixed. Please open a separate issue for HTML support.
