### ISSUE TITLE
Epub format is no longer mobile-friendly

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#125]
Due to how the format is no longer made to make words stay within the screen's borders and instead following the formatting taken directly from the site, when the epub file is taken from a computer, where the epub reader's window can be expanded at will, to a mobile device, it becomes less like a 'scroll' and more like I just copy-pasted a webpage from a pc and viewing it from a mobile device, requiring me to horizontally scroll back and forth to read a whole sentence. Repeating the process hundreds of times for really long fics with long sentences while also needing to scroll downwards to continue the story is very tedious and changing the positioning of the screen from vertical to horizontal does not help.

Is this problem related to the re-addition of the PDF format and can you fix it?

**Comment by waylaidwanderer** [comment]
Yes, you're right. I've fixed this.
