### ISSUE TITLE
Prone to failure to download and failure to find the story.

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#130]
There is a problem with the site's stability. For eight hours or more it went on and off by the minute with only a few windows of opportunities to download fics, and now it's somewhat more stable, but it's impossible to download fics that has 5 or more chapters because it keeps on getting errors, and repeated attempts to download the same fic only makes it worse, e.g., at first I was able to download nine chapters of a fic before it stopped, then when I try again, the number dropped to six, then it dropped to two until it stops trying at one. What could be the cause of this? Is it the server and can you fix it?

**Comment by waylaidwanderer** [comment]
Hi, I've just pushed a fix. I'm assuming you're trying to download Fanfiction.net fanfics, which is what I tested with. The site itself seems to be giving empty responses after a while. I added a retry which seems to workaround the issue, please let me know how it goes in the long term.

**Comment by peterberbec** [comment]
Seems to be working great, thanks!
