### ISSUE TITLE
Error: Failed to download

### ISSUE THREAD

**Issue by EasyJade** [waylaidwanderer/FicSave#131]
Continuously getting the Error: failed to download chapter message. Have tried multiple fan fictions to experiment and all have the same result. They download a few chapters then the error pops up. Any ideas?

**Comment by peterberbec** [comment]
Happening to me too. Almost always gets ch. 1, sometimes 2, 3 and 4 (rarely) but that's it.

**Comment by waylaidwanderer** [comment]
Duplicate of #130, conversation will continue there.
