### ISSUE TITLE
Corrupt mobi file? 

### ISSUE THREAD

**Issue by smithm31** [waylaidwanderer/FicSave#132]
I've used to your website previously with no issue. However, today I am not receiving mobi files to my Kindle even though the website says the e-mail has been sent. I tried sending it to my personal account and downloading via USB - that also didn't work. I tried Calibre to convert from Mobi to AZ3 to see if that was the issue, and it says the Mobi file is corrupt.

**Comment by waylaidwanderer** [comment]
What happens if you download the epub and then convert it to mobi? If that works, it might be a problem with the fanfic itself, or are you experiencing this issue with multiple stories?

**Comment by juliadoan** [comment]
I am having the same exact issue

**Comment by waylaidwanderer** [comment]
Should be fixed now.
