### ISSUE TITLE
Emailed epubs not opening

### ISSUE THREAD

**Issue by krysangl** [waylaidwanderer/FicSave#133]
When trying to open the ePub stories that have been emailed they do not open.  When in nook app they show an error but do not say what the error is.  It started with stories in ePub I had emailed on 7/7.  I tried them again today still not opening.

**Comment by waylaidwanderer** [comment]
What site are you downloading them from? I just tried downloading an epub from ff.net via email and it worked for me.

**Comment by krysangl** [comment]
Downloading from FFN. Tried opening on iPad and iPhone, in regular mail and the ymail app.  Tried opening in iBooks, Nook, and Kindle apps. 

Krysangl

**Comment by waylaidwanderer** [comment]
Is it one particular fanfic or multiple ones, and is it the issue still occurring?

**Comment by krysangl** [comment]
It was 4 different fics.  They will open when I download directly from the site but not when I have them emailed.  I tried it again just now and it still won't open, still getting an error loading book message in Nook.  I have tried books from previous days and they open fine. The email is also different than normal, not sure if this makes a difference or not.  

Regular email


Email that won't open


Krysangl

**Comment by waylaidwanderer** [comment]
I can't see the images, can you upload them to a site like imgur instead?

**Comment by krysangl** [comment]
Here is the links for imgur:

Regular - https://imgur.com/1cuypee

Not working- https://imgur.com/porFy36

Krysangl

**Comment by waylaidwanderer** [comment]
I think I have an inkling of the issue, but in the meantime, could you try using a different email app and see if it works? (Something like Gmail, Inbox or Outlook)

**Comment by krysangl** [comment]
Sent it to my outlook account and tried opening in app and online still not opening.  Thank you for trying to fix it and for building/maintaining the ficsave site.

Krysangl

**Comment by weber-lane** [comment]
Hello,

I am having the same issue as well.  If I download my .epub directly from ficsave.xyz, it will open fine.  If I have it emailed to any of my email address (mac.com, gmail.com, hotmail.com, yahoo.com) the .epub attached to the email will not open. Attached is one of the epubs emailed that will not open.
[emailed-will not open.epub.zip](https://github.com/waylaidwanderer/FicSave/files/368090/emailed-will.not.open.epub.zip)

Not a big deal, but it was kinda handy emailing the epubs.  I have went back to saving them directly to my Dropbox, like I did before I found Ficsave.  Thank you for your all you do regarding Ficsave!

**Comment by waylaidwanderer** [comment]
Hi all, I just pushed a commit (https://github.com/waylaidwanderer/FicSave/commit/a1141beee7244fa6e3e6476d315af53b4a9a1616) that attempts to fix the corrupted ebooks being mailed out.

Please let me know if it's working!

**Comment by weber-lane** [comment]
Thank you!!!  I submitted 2 from FFN and it worked as expected.

**Comment by krysangl** [comment]
It is working again, thank you for fixing this issue.
