### ISSUE TITLE
Cannot download in Android Firefox, In Browser, etc. (Chrome works)

### ISSUE THREAD

**Issue by apukwa** [waylaidwanderer/FicSave#134]
On every android device I have available to me, files from FicSave only work if downloaded through Chrome.  This started after the June 16 change.

I'm not sure what to give you, but I hooked up WebIDE and captured the headers, etc. for the request of the download file and here they are below:

Request URL:http://ficsave.xyz/download/578088d7262eb
Request Method: GET
Remote Address: http://ficsave.xyz/download/578088d7262eb
Status Code: 200 OK
Version: HTTP/1.1
**Request Headers:**
Host: ficsave.xyz
User-Agent: Mozilla/5.0 (Android 5.1.1; Mobile; rv:47.0) Gecko/47.0 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en-CA;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://ficsave.xyz/?url=https://m.fanfiction.net/s/8547238/1/The-Water-Witch-and-the-Black-Dogs&format=epub&download=yes
Cookie: __cfduid=dde808ee495a4df1325c83ff9f7a6354d1466657068; _ga=GA1.2.695696160.1466657071; XSRF-TOKEN=eyJpdiI6ImszMVpVTWdqNzg3WUorTVwvT2RaNHNRPT0iLCJ2YWx1ZSI6IlBaYVptZVVCVjlCZktSVGR2bktYRGNtSkRWeUVRQ0JvNDh5d2NJTXFxV1lDaXJvUk5BTjVIU2VzWm4xY2MrTnpyMWV3NHpTTVArclNmcWkyUDBNSGlnPT0iLCJtYWMiOiJmOGFkMDdmOGI2ODJhZDQ5NDAyNGFkZDgwOTRlNjc1OWI5NDAzN2ZhZjRhNDM4NzA4ODNkMjViY2YyOTVmZTY0In0%3D; laravel_session=eyJpdiI6Ik90SkIxMndxNHljbVwvdGtqbDBzcUNRPT0iLCJ2YWx1ZSI6IldMYXFRbzcya1NncXN6MVhTN2VGXC9zdWJxSnU4RFpuZ1NsSEhIeCt0bFdoUGpJNkl1MEpJN0JTNVB5KzVSK2RCd01EeUZBMytLbzJPb1VGQXZYV2lcL0E9PSIsIm1hYyI6IjA2ODgyZmE2MzkzN2EwOWU2OWYwMDIwMzliZGIzZDhlODAzOWZmNWE3ZjVmOWFjMjE2Yzc2NmI2YWE1M2I4YWEifQ%3D%3D; _gat=1
Connection: keep-alive

**Response Headers:**
Host: ficsave.xyz
User-Agent: Mozilla/5.0 (Android 5.1.1; Mobile; rv:47.0) Gecko/47.0 Firefox/47.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en-CA;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://ficsave.xyz/?url=https://m.fanfiction.net/s/8547238/1/The-Water-Witch-and-the-Black-Dogs&format=epub&download=yes
Cookie: __cfduid=dde808ee495a4df1325c83ff9f7a6354d1466657068; _ga=GA1.2.695696160.1466657071; XSRF-TOKEN=eyJpdiI6ImszMVpVTWdqNzg3WUorTVwvT2RaNHNRPT0iLCJ2YWx1ZSI6IlBaYVptZVVCVjlCZktSVGR2bktYRGNtSkRWeUVRQ0JvNDh5d2NJTXFxV1lDaXJvUk5BTjVIU2VzWm4xY2MrTnpyMWV3NHpTTVArclNmcWkyUDBNSGlnPT0iLCJtYWMiOiJmOGFkMDdmOGI2ODJhZDQ5NDAyNGFkZDgwOTRlNjc1OWI5NDAzN2ZhZjRhNDM4NzA4ODNkMjViY2YyOTVmZTY0In0%3D; laravel_session=eyJpdiI6Ik90SkIxMndxNHljbVwvdGtqbDBzcUNRPT0iLCJ2YWx1ZSI6IldMYXFRbzcya1NncXN6MVhTN2VGXC9zdWJxSnU4RFpuZ1NsSEhIeCt0bFdoUGpJNkl1MEpJN0JTNVB5KzVSK2RCd01EeUZBMytLbzJPb1VGQXZYV2lcL0E9PSIsIm1hYyI6IjA2ODgyZmE2MzkzN2EwOWU2OWYwMDIwMzliZGIzZDhlODAzOWZmNWE3ZjVmOWFjMjE2Yzc2NmI2YWE1M2I4YWEifQ%3D%3D; _gat=1
Connection: keep-alive

**Comment by waylaidwanderer** [comment]
Thanks for your tweets and issue. However, I'm unable to reproduce it. Downloading fanfics works in both Chrome and Firefox on my device.

`Status Code: 200 OK` indicates that the request was made correctly, so it may be something on your end.

**Comment by pylerSM** [comment]
Hello, are you gonna open source Power Nap xposed module? So we can continue development.
