### ISSUE TITLE
"A server error has occurred"-error all the time

### ISSUE THREAD

**Issue by Arw165** [waylaidwanderer/FicSave#136]
I can't download anything since yesterday (for more than 25h). Every time I enter the site, I'm informed "A server error has occurred. Please try again later". It appears immediately on its own, before I even have a chance to do anything. And after I actually press "download". Refreshing doesn't help (it usually did in the past). It's first time for me to have this problem, is it only on my side?

**Comment by smoov22** [comment]
This happens on my iPhone 5S, but not my iPad.

**Comment by smoov22** [comment]
This happens on my iPhone 5S, but not my iPad.

**Comment by Arw165** [comment]
Problem solved, though I don't exactly know what the problem was. I probably had old site bookmarked as "https://ficsave.com" and later just changed the ending to "xyz" and it stopped working. Site works, if I type only "ficsave.xyz", but I'll admit "server-error" appears more often than it used to, especially if I leave the site open after downloading and don't use for some minutes (I have to refresh it to donwload another file after this pause). But it's not that much big of a problem.

**Comment by tsolid** [comment]
I had the same problem when I went to https://ficsave.xyz/ but when I remove the SSL and go to http://ficsave.xyz/ everything works fine with no error.

**Comment by waylaidwanderer** [comment]
I've added a rule to redirect https:// to plain ol' http:// - let me know if this helps.

**Comment by Arw165** [comment]
Works fine, thank you. This site is the greatest invention since the wheel.

**Comment by waylaidwanderer** [comment]
Great to hear!
