### ISSUE TITLE
email not working (see notes below)

### ISSUE THREAD

**Issue by adquintero2230** [waylaidwanderer/FicSave#141]
Hi,  
I set up the bookmarklet for the new ficsave.xyz site.  When I attempt to download a story from Fanfiction.net the email that I entered in the bookmarklet has the following example of extra symbols: "myemail@gmail.com"/   This causes a "failure to send email" error message because of the extra symbols.  
IF I try to add a story from the main Ficsave.xyz site and copy/past the story link and use the correct email address format without the symbols.  The email is sent successfully upon completion. HOWEVER, when I attempt to open it for my Kindle Fire, the story does not open.  HELP

**Comment by waylaidwanderer** [comment]
Duplicate of #133

**Comment by waylaidwanderer** [comment]
Also this has been fixed now.
