### ISSUE TITLE
Error Failed to Create eBook

### ISSUE THREAD

**Issue by xXShiina** [waylaidwanderer/FicSave#142]
I keep getting "Error Failed to create Ebook" :( I'm on Firefox 47.0.1 for Windows 7 64Bit.

**Comment by waylaidwanderer** [comment]
Fixed.

**Comment by xXShiina** [comment]
This was not fixed. I still have the error.

**Comment by waylaidwanderer** [comment]
Well, you'll have to give me more details to go on, as I assumed it was related to the email bug others were having. It would be helpful to know the URL of the fanfic as well as format.

**Comment by xXShiina** [comment]
Sorry for not providing enough information on the error that was my mistake. I am indeed using the optional email option with the Epub format. 

Also it seems that its not just one link, I just tested it with other links on FanFiction.Net and none of them worked. I got the error "failed to build Ebook".

These are the stories I'm trying to convert and download, Granted these are only 4. I have many more I want to download.

https://www.fanfiction.net/s/11537548/1/The-Yotsuba-s-Trepidation
https://www.fanfiction.net/s/12057432/1/Crimson-Devil-s-Island-Caf%C3%A9
https://www.fanfiction.net/s/12024005/1/2092-Aftermath
https://www.fanfiction.net/s/11689604/1/The-Devil-and-the-Hero-Forgive-and-Forget

**Comment by waylaidwanderer** [comment]
I think I fixed it for real this time. Can you recheck?

**Comment by xXShiina** [comment]
Looks good! Its working :).

Thank you!

**Comment by waylaidwanderer** [comment]
Great to hear.
