### ISSUE TITLE
I want to donate but I can't

### ISSUE THREAD

**Issue by laura10** [waylaidwanderer/FicSave#143]
Hi, 
I've recently discovered FicSave and it's amazing! I would love to contribute but I've been unable to donate. There's a problem with the province (only have canadian options) and the phone number (I've tried with the country code but it says it doesn't exist). 
I'm from Spain, btw.

**Comment by waylaidwanderer** [comment]
If you can't donate, it's okay! Thank you for the thought, I appreciate it all the same.
