### ISSUE TITLE
POST ISSUES ABOUT SITE UPDATE HERE

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#148]
The site doesn't seem to be able to retrieve any story. When a link is typed and entered, it just stayed on 'Loading...' for a long time. Might there be some problem in the server, or is this related to the changes you've made recently?
EDIT: It IS because of the changes you've made recently. You've changed it in a way that made it no longer proxy-friendly. I live in a country where fanfiction.net is blocked by my ISP, so I require a proxy add-on in my browser to access it, and because of the way ficsave now streams the downloads, it has somehow become impossible for me to use the site, because even if I turn the proxy off, your site won't download any fic either because of the block. Please, can you make it proxy-friendly again somehow?

**Comment by Arw165** [comment]
Had the same problem, but it changed now to "The url format is invalid". Still can't download anything.

**Comment by Cyrianu** [comment]
Hello,

I'd like to confirm that this isn't just an issue for those behind a proxy server.

I get the green DOWNLOAD button stuck on "LOADING..." and the story status on Pending, then eventually "A server error has occurred. Please try again later." pops up.

**Comment by Arw165** [comment]
It's back to"server error" now, but it doesn't get even to the "pending" stage on my end.

**Comment by sirius16** [comment]
I concur, I'm also experiencing the perpetual "pending" problem as well, also very recent. Can confirm it's not unique to one site (FF.net) but occurs on others as well (AFF.net)

**Comment by waylaidwanderer** [comment]
Hi guys, I think I fixed the issue. However it could have been something else unrelated to what I fixed, so please inform me if this happens again.

**Comment by Arw165** [comment]
Just downloaded two fics, seems to work ok now.

**Comment by Cyrianu** [comment]
Worked perfectly on the one I'd been trying to download, and it was super-quick to download too.  Seems a bit speedier with multi-chapter fics as well compared to previously.

**Comment by waylaidwanderer** [comment]
@Cyrianu yeah, that was my goal. It remains to be seen how well the server will hold up against heaver load.

**Comment by Cyrianu** [comment]
One thing I am noticing with very high chapter count fic, is that around chapter 94/95, it seems to blink back and forth between a very early chapter number and the one it's supposed to be downloading, but it does seem to download the proper information overall...  Here's an example to see this for yourself: https://www.fanfiction.net/s/11272126/

**Comment by waylaidwanderer** [comment]
Haha, I see what you mean. I'll have to investigate what's causing it.

**Comment by sirius16** [comment]
Yes, can confirm it is once again working. Thank you

**Comment by waylaidwanderer** [comment]
@Cyrianu I've fixed the issue for you.

**Comment by Cyrianu** [comment]
Much appreciated, @waylaidwanderer.  :)  Thanks for your time and effort in maintaining the site.  At some point I may be in touch looking for info on setting up my own personal mirror.

**Comment by Walkingwalkerwalks** [comment]
It works now, but there is a catch.
I can download fics just fine, but if I opened the site using a proxy or if I left it idle for too long while using a proxy, like thirty seconds, it won't show that it's loading the fic until I turn the proxy off and reload the site, in which case the fic will pop up, and I'll be able to download them.
I can work with it just fine despite the very slight inconvenience, all I need to do is to turn it on and off a couple of times. Thank you so much for fixing the initial issue, but if there's anything you can do on your end to fix this particular one, I'd appreciate it.

**Comment by waylaidwanderer** [comment]
@Walkingwalkerwalks 
1. What browser addon are you using? 
2. And it's definitely a proxy, not a VPN?
It works fine when I use a VPN, just fyi, so perhaps you can look into one of those like PIA or AirVPN (I've used both in the past, currently using AirVPN which gets around Netflix region blocks).

**Comment by Walkingwalkerwalks** [comment]
Anonymox.

Addendum: I've tested with another similar add-on, and it works fine, I think the problem lies with just Anonymox.

**Comment by Arw165** [comment]
Can't download anything again, for many hours now, don't know the reason. I put url link, click Download, after few seconds of Loading it goes back to Download (like it should to), but nothing appears below, story doesn't get loaded. There's no notification about any errors.

**Comment by Cyrianu** [comment]
As a follow-up to Arw165, this does not appear to be a global issue.  Tested via going to site fresh, entering URL for testing (https://www.fanfiction.net/s/11593847/), and successful processing occurred.

**Comment by Walkingwalkerwalks** [comment]
The problem in loading stories seems to have popped up again, it's exactly like how it was 3 days ago when I first posted this issue, a link is typed and entered, but it just stayed on 'Loading...' indefinitely. Even without using a proxy, it just stays on 'Pending...' for a very long time with no progress.

**Comment by waylaidwanderer** [comment]
Should be working again.

**Comment by Arw165** [comment]
Works on my end.

**Comment by Walkingwalkerwalks** [comment]
It happens again. Same problem as before.

**Comment by waylaidwanderer** [comment]
I found the issue. There was a job stuck in the queue, causing other downloads to not start.

**Comment by waylaidwanderer** [comment]
Working on fixing it.

**Comment by waylaidwanderer** [comment]
Should be fine now, but I haven't figured out why it gets stuck like that.

**Comment by darkknitex-6** [comment]
Hi, I'm having a problem since the new update. Seems to affect browsers that use a server-side redirect or server-side compression like the OperaMini and UCBrowser.
The previous version didn't have this issue.
Clicking on the link to download a file, clears the file link like normal but no download link appears :(
Is it possible to have a link to the previous version?
Thanx

**Comment by Arw165** [comment]
So it's not only me (I have the same problem on firefox, on IE everything works fine).

**Comment by waylaidwanderer** [comment]
@darkknitex-6 The server uses websockets to communicate the download progress, which means it must be able to communicate with the client (aka you) directly, and not via a proxy like OperaMini. I'll have to see if there is a workaround for this.

**Comment by darkknitex-6** [comment]
Thanx for the reply.
Just to clarify, OperaMini supports both web-socket and http protocols. 
One set uses just http, the other uses a combination of web-socket and http. It just depends on your setup.
The previous version worked using either setup.
Thanx.

**Comment by waylaidwanderer** [comment]
Apparently Opera Mini doesn't work with web sockets. http://caniuse.com/#feat=websockets

**Comment by darkknitex-6** [comment]
Thanx.
Wasn't aware of that. My reply was based on the advanced settings in operamini.
Didn't think to actually do websearch on compatability :(

**Comment by granthall** [comment]
Think there might be another stuck job right now. Stories are all pending for me. 

Great job on the site by the way. made reading fanfics a million times more enjoyable.

**Comment by waylaidwanderer** [comment]
@granthall Restarted some stuff and it seems to be working again now. Thanks for letting me know.

**Comment by FicsaverUser** [comment]
I can't seem to read this story
Here's the link
https://www.fanfiction.net/s/12482053/1/SIS-Diamond-Pearl-Adventures
After downloading it into iBooks, it told me that it can't be read because it is formatted incorrectly for iBooks.
