### ISSUE TITLE
Emails Not Being Delivered to Kindle

### ISSUE THREAD

**Issue by ajs526** [waylaidwanderer/FicSave#156]
Hi,

  The fics that I saved using FicSave are not being delivered to my Kindle. The site says that the email is sent but they are not delivered. 

Alyssa

**Comment by waylaidwanderer** [comment]
Kindle is blocking the methods I used to send ebooks. Unfortunately it won't work properly. You can try sending it to your own email and creating a forwarding rule that automatically sends it to your kindle.

**Comment by waylaidwanderer** [comment]
See #150
