### ISSUE TITLE
"encyrpted section" where there should be a chapter 

### ISSUE THREAD

**Issue by complaining-user-engine** [waylaidwanderer/FicSave#163]
I followed these steps:

Copied and pasted this link into fic url field: https://m.fanfiction.net/s/12327523/1/Ranma-Happenstance-Gone-Right

Entered an email address to send fic in EPUB format

Opened in fbreader for android(f-droid version) and upon going to the forth chapter I got the encrypted section message.

This was repeated to ensure it wasn't a one time thing. Up until recently I've had no issues using ficsave i

**Comment by complaining-user-engine** [comment]
Just tested with the document viewer app(also from f-droid) and I could read it. So may be a bug in the fbreader app rather than ficsave itself.

**Comment by waylaidwanderer** [comment]
Alright. Thanks for letting me know anyway.

**Comment by Stevko-sk** [comment]
I believe it is a bug in fbreader and it seems to happen when chapters have non ascii characters in their (file)name. For example ellipsis (…) in ``<item id="chapter14" href="Some chapter….html" media-type="application/xhtml+xml" />`` As a workaround, could you make all filenames in epubs ascii only (for example just name them chapterXX.html)?
