### ISSUE TITLE
Stuck on Pending/'Pending' Delay (Again)

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#165]
This issue is very similar to the one you closed back in March 18, -I was also the one who reported it-, where it takes quite a long time for a story to be downloaded while all the while, the progress on getting the chapters remain stuck on 'Pending' until it actually starts.

**Comment by Walkingwalkerwalks** [comment]
It's happening again, the download progress is stuck at 'Pending' could you please check it out?

**Comment by Shannon83k** [comment]
Having same issue

**Comment by Arw165** [comment]
For more than 15 hours or something.

**Comment by FicsaverUser** [comment]
I'm stuck at pending.

**Comment by waylaidwanderer** [comment]
Fixed now :)
