### ISSUE TITLE
Stuck on Pending (Slow Download Version)

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#176]
It is much slower than usual for the site to download any stories, the same problem that occurred 8 days ago, which you solved by restarting everything and clearing the queue.

**Comment by Walkingwalkerwalks** [comment]
Update: It's happening again.

**Comment by Arw165** [comment]
It's stuck on pending for minutes, before it actually starts converting. It wasn't like that before (as in "till few weeks ago"). Is it something we are going to have to get used to?

**Comment by waylaidwanderer** [comment]
Should be working normally again.
