### ISSUE TITLE
Stuck on Loading that Ends up either on 'Server Error' or 'Could not Retrieve Story'

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#186]
I don't know how long this has been going on, but just a few minutes ago, I tried using the site, and it could not stop 'Loading...' or sometimes it ends up having the 'Server Error' or 'Could not Retrieve Story' message. Is there something wrong with the server? Before this, there has been some hiccup as well, yesterday, it took a while for fics to be loaded and ready to be downloaded as well. At the time, it didn't take a long time for the fics to be loaded, so I didn't report it but could there be a problem with the server?

**Comment by waylaidwanderer** [comment]
Should be fixed now.
