### ISSUE TITLE
Pending Delay/Stuck on Pending

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#191]
Just tried this a few seconds ago, so I don't know how long it has been going on, but the fics that are queued are stuck on 'Pending' for quite a while before it really starts getting downloaded. Sometimes, it takes so long that the moment it's finished downloading the chapters and has built the e-book, it disappears immediately from the queue. Sometimes, it wouldn't even download it at all.

**Comment by waylaidwanderer** [comment]
Should be good now
