### ISSUE TITLE
Nothing Downloads

### ISSUE THREAD

**Issue by shadowsspy** [waylaidwanderer/FicSave#199]
I was trying to download the following fanfictions as text but when i tried Cruento Puella which only has 1 chapter it never finished and instead after waiting over 10 minutes it acted like it had finished but gave me no download link on the page and no download auto started and its been a at least 3 hours probally more since i tried via email and nothing has showed up. Edit Went threw fine on my tablet and when i tried PC again it was solved
https://www.fanfiction.net/s/3987309/1/Cruento-Puella
https://www.fanfiction.net/s/8368857/1/Allergic-to-Potions
https://www.fanfiction.net/s/1925624/1/Bringer-Of-Death

**Comment by Arw165** [comment]
It's eternal "pending" for me as well, I tried downloading anything for the last 20h with no success.

**Comment by Chesshur** [comment]
It's been very erratic with me it sometimes gets stuck on "pending" for as long as half an hour if I'm trying to do a multi-chapter fic. Even single chapter stories occasionally lag, sometimes up to 5 minutes before downloading.

**Comment by waylaidwanderer** [comment]
@Chesshur what site are you trying to download from? Is this still going on?

**Comment by Chesshur** [comment]
This mostly happens with fanfiction.net and it's been an off and on issue with me. Some times I can download with no problems some times there is a lag.

**Comment by waylaidwanderer** [comment]
I gave things a restart so it should be better now.
