### ISSUE TITLE
Pending Delay and Slow and Stuttering Download Progress

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#201]
Just tried using the site a few seconds ago so I don't know how long this has been going on. The fics that are queued are stuck on pending for a very long time. Then, once it's starting the download, the chapters are downloaded slower than it usually was with some odd pauses at times before resuming. And with how long it took to get a fic to start downloading, sometimes the queued fics would disappear for a moment. At best, they would pop back up and show that its chapters are getting downloaded and at worst, they're just gone and thus needs to be queued again.

**Comment by waylaidwanderer** [comment]
Gave things some good ol' percussive maintenance.
