### ISSUE TITLE
Server Error: Failed to Download Chapter

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#202]
This problem is a combination of issue #186 and issue #190  in which the link of a story is entered and results in either two possibilities: 1. It's stuck on 'Loading...' before a message pops up saying 'A server error has occurred. Please try again later.' and the site has to be refreshed so that the link can be tried again, in which case: 2. It starts downloading, gets stuck on one random chapter and either it starts downloading again until it finishes or it's stuck for so long that it fails to download the whole thing, making it impossible if not tedious to download a story with multiple chapters.

**Comment by waylaidwanderer** [comment]
I gave everything a restart, let me know if it happens again.
