### ISSUE TITLE
Site Seems to Be Down

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#205]
I don't know how long it's been going on, but trying to access the site seems impossible. It keeps saying 'Waiting for ficsave.xyz...' perpetually. Is the server completely unresponsive?

**Comment by waylaidwanderer** [comment]
Yeah, you're right. I'm not sure what happened exactly, but the entire server was unresponsive. I had to power-cycle it from DigitalOcean's control panel. Anyway, it's working again. Thanks for letting me know.
