### ISSUE TITLE
Ficsave overwhelmed by number of chapters

### ISSUE THREAD

**Issue by purrfus** [waylaidwanderer/FicSave#210]
Attempted to use the site for a ffn Nobody Ever Asked My Birthday by SkyeMoor. The fic is 323,605 words and 490 chapters. I have used the site for fics upto 800,000 words without issue. I think the problem is the number of chapters. I have tried all of the formats without success.

**Comment by purrfus** [comment]
Tried again. It seem to be downloading the chapters in order upto chapter 82. I stepped away, and when I looked again it went from CH 88 to CH 12 to CH 129. I stopped it and will try again later. Is there a low use time for the site that might be best?

Thanks
 
 
 
-----Original Message-----

**Comment by waylaidwanderer** [comment]
Hmm, try letting it run until completion and let me know what happens. I don't think low use times would matter.

**Comment by waylaidwanderer** [comment]
Try https://beta.ficsave.xyz

**Comment by purrfus** [comment]
Hi

I tried it today. It is set on epub and showed the download as percentages instead of the other page's chapters.

I opened the book and it seems to be working. 

Wow.

I'll do some reading this weekend and let you know for sure.

Thanks so much!

G
 
 
 
-----Original Message-----
