### ISSUE TITLE
Unable to copy to IBOOKS

### ISSUE THREAD

**Issue by frogiea** [waylaidwanderer/FicSave#211]
Precious to updating to latest IOS, worked fine. Now I get a different question if I want to Download already downloaded URL

**Comment by waylaidwanderer** [comment]
Can you try a different browser on iOS?

**Comment by frogiea** [comment]
GMTA
I was just about to download one.
Will let you know the results

Joan
Cell : 917-751-3684

> On Oct 30, 2019, at 11:06 PM, Joel <notifications@github.com> wrote:
> 

﻿
Can you try a different browser on iOS?

**Comment by frogiea** [comment]
I tried  firefox. Somhow ibooks is not accessible to either browser.
This is the safari loop message
Firefox let me email myself the epub.



Joan
Cell : 917-751-3684

> On Oct 30, 2019, at 11:06 PM, Joel <notifications@github.com> wrote:
> 

﻿
Can you try a different browser on iOS?

**Comment by waylaidwanderer** [comment]
Try Chrome? Not sure what the issue is though, I don't use iOS myself.

Joan, you should remove your email signature. It includes your name and phone number which is now posted publicly.

**Comment by waylaidwanderer** [comment]
I've just edited your messages for you to hide that information.

**Comment by frogiea** [comment]
thanks
never used Github before


> On Oct 30, 2019, at 11:54 PM, Joel <notifications@github.com> wrote:
> 

﻿
Try Chrome? Not sure what the issue is though, I don't use iOS myself.

Joan, you should remove your email signature. It includes your name and phone number which is now posted publicly.

**Comment by frogiea** [comment]
Chrome worked
Safari on the updated IOS on phone and Ipad seem to have changed and faid
Figures

> On Oct 30, 2019, at 11:54 PM, Joel <notifications@github.com> wrote:
> 

﻿
Try Chrome? Not sure what the issue is though, I don't use iOS myself.

Joan, you should remove your email signature. It includes your name and phone number which is now posted publicly.

**Comment by waylaidwanderer** [comment]
Glad to hear Chrome works. I'll mark this as resolved.

**Comment by frogiea** [comment]
Finally did a reload of my ipad from a backup, reupdated, now it is working, just a bit differently.
Thanks for your help
Joan

> On Oct 31, 2019, at 8:54 AM, Frog Reads <frogreads@aol.com> wrote:
> 

﻿thanks
never used Github before


> On Oct 30, 2019, at 11:54 PM, Joel <notifications@github.com> wrote:
> 

﻿
Try Chrome? Not sure what the issue is though, I don't use iOS myself.

Joan, you should remove your email signature. It includes your name and phone number which is now posted publicly.
