### ISSUE TITLE
MOBI format downloads repeatedly giving "File not found" errors while epub works

### ISSUE THREAD

**Issue by rmunn** [waylaidwanderer/FicSave#214]
When I try to download a fanfic like https://www.fanfiction.net/s/3218251/1/Witchy-Woman in MOBI format, I repeatedly get to the step where the file should start downloading, and instead I get `File not found: /var/www/ficsave.xyz/storage/app/tmp/5dd10cf49e080_What-Comes-Around-Vathara.mobi` as the only text on a blank white page. (The numbers, of course, are different each time). This has happened several times over the past few days, with several different fics. Epub files of the same fic seem to be downloading just fine without any issues.

**Comment by waylaidwanderer** [comment]
Hmm, sounds like an unhandled issue in the conversion process. I'd suggest for now, just download the epub version and convert it to mobi. In the meantime I'll look into the issue.

**Comment by rmunn** [comment]
Appears to be fixed now; at least, I was just able to download three different .mobi files. I'll reopen if the problem shows up again.
