### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#217]
Don't know how long this has been going on, just tried using the site about a minute prior to this writing and after typing in the link and pressing enter, the result is either 1.) 'A Server Error has occurred, please try again later' message popping up immediately. 2.) It goes to 'Loading...' for a few seconds but then the same message above ends up popping up anyway. and 3.) The message "A new session has been started in a different window! Please switch to the new session or refresh the page." pops up even though the different window doesn't pop-up and refreshing the page for a retry would result in repeating either number 1 or number 2 above.

Usually, a site refresh would work for any of the three aforementioned situation because they tend to happen sometimes, but this time, it keeps on happening and rendering the site unusable.

**Comment by Arw165** [comment]
The same for me. Couldn't download anything whole day.

**Comment by waylaidwanderer** [comment]
Thanks for reporting the issue. I had to replace all the proxies I was using, but the site should be working again.
