### ISSUE TITLE
Stuck on Pending/Pending Delay/Slow Download

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#220]
Hello. Firstly, I mostly use ficsave for ffdotnet. Secondly, I was busy when you fixed it so I didn't manage to check it and right now, at the time of this writing, it seems to be having the Stuck on Pending Problem again. Will edit this if it turns out to be a Pending Delay.

Edit: It's the same problem again. I'll open up a new issue.

_Originally posted by @Walkingwalkerwalks in https://github.com/waylaidwanderer/FicSave/issues/219#issuecomment-565015742_

**Comment by Walkingwalkerwalks** [comment]
Yes, it's the same problem again. Maybe whatever is making the problem is related to the new proxies you replaced the old ones with six days ago, back during the Server Error problem? I noticed that since you fixed that particular problem, the 'Loading...' time takes a bit longer than usual so maybe that's why?

**Comment by Walkingwalkerwalks** [comment]
Update: I managed to download one fic. However, the catch is this: The 'Pending' gets stuck for a very long time and then the progress disappears entirely like 'Stuck on Pending' usually is. But then, the download progress pops back up and starts downloading the chapters but it does so **very slowly.** Getting only one or less than ten chapters downloaded takes a short time but currently, I'm trying to download a fic with 30+ chapters, which would probably take ten or more minutes if it doesn't just fail to do so in the middle.

**Comment by Walkingwalkerwalks** [comment]
Update: It takes a while, but the fic with 30+ chapters has been downloaded. Even the 'Building eBook' progress is a bit slow as well.

So to sum up: This is a 'Pending Delay' problem that first appears like it's 'Stuck on Pending' problem with the addition of 'Slow Download' problem. As I wrote above, maybe it is related to the proxies being used?

**Comment by Walkingwalkerwalks** [comment]
Anyway, sorry for the long thread, but I was dealing with the problem changing itself live when I started writing the issue.

**Comment by waylaidwanderer** [comment]
Hey, thanks for the info. I'll look into it.

**Comment by waylaidwanderer** [comment]
Okay, things should be better now, but I'll keep looking into the issue.

**Comment by Walkingwalkerwalks** [comment]
Hello. It looks like it's acting up again. For now, it seems to be 'Stuck On Pending', but I will edit this if it in about ten minutes from now if turns out to be like before where it downloads the story long after the download progress disappears or it's actually 'Stuck on Pending' and the download progress disappears for good.

**Comment by Walkingwalkerwalks** [comment]
Edit: It is the same problem as before, the download progress pops back up after a while (about five to seven minutes after the download progress disappears, at best) and starts downloading the chapters. Unlike the last time this happened though, the download speed per chapter is just like usual instead of being slow like before.

**Comment by waylaidwanderer** [comment]
Restarted everything again.

I've done some more work on a rewrite of FicSave (2.0) in the past few days. Hopefully can get a Minimum Viable Product out under beta.ficsave.xyz soon.

**Comment by Walkingwalkerwalks** [comment]
Hello, just want to give another update: The server is acting up again and causing a Pending Delay problem. However, this isn't as bad as before because the download progress would start without disappearing first and the download progress per chapter is as fast as it usually is.

**Comment by waylaidwanderer** [comment]
Gave it another restart btw

**Comment by Walkingwalkerwalks** [comment]
Thank you, but it seems that at the time of this writing, the Pending Delay problem is happening again. It's exactly like before, it takes minutes between 'Pending' and the chapters getting downloaded but once they start getting downloaded, it's just as usual.

**Comment by Walkingwalkerwalks** [comment]
Edit: Disregard my previous comment, the Pending Delay problem is happening in the same way it did about four days ago where the download progress disappears for a while and then suddenly pops back up and starts downloading the chapters.

**Comment by waylaidwanderer** [comment]
Okay, I think I know what's going on. I scaled down the number of workers (processes that handle the queue to download stories) in an attempt to stop the server from running out of resources so often, but I may have gone a bit too far, causing a bottleneck when a lot of people are trying to download fanfics at once. I've increased the number of workers by a bit, so let me know if it happens again.

**Comment by Petersenf** [comment]
This issue is still happening. Haven't been able to download anything in the last 14 hours.

**Comment by waylaidwanderer** [comment]
Fixed it for now. I think some epub -> PDF conversions are getting stuck. I may need to disable the PDF option on the site.

**Comment by Walkingwalkerwalks** [comment]
Hello, I don't know how long it has been going on now but at the time of this writing, the problem is happening again. It's the Pending Delay problem where the download progress of the queued fics disappear after being stuck on pending for so long and then they suddenly reappear to start downloading the chapters. In addition to that, once it's started, the download speed for the chapters is slower than usual and it can only download the chapters of one queued fic at a time instead of downloading the chapters of more than one queued fic simultaneously.

**Comment by Walkingwalkerwalks** [comment]
As of this writing, the problem seems to have devolved into real 'Stuck on Pending' problem with no queued fics getting downloaded. I will open up a new issue.

**Comment by Walkingwalkerwalks** [comment]
Update: Disregard the above comment, the problem is the same as yesterday.

**Comment by Walkingwalkerwalks** [comment]
Hello. Just in case you haven't read my previous comments, the problem with the Pending Delay is still going on right now.
