### ISSUE TITLE
Duplicate Emails

### ISSUE THREAD

**Issue by BenGiles123** [waylaidwanderer/FicSave#221]
Hi, I tried to convert a fic to Mobi and receive by email, but I’m now being sent a 1 byte file every couple of hours.

Could you kill whatever is resending the file please?
Email address is ben@extremegb.com.

Merry Christmas!

**Comment by waylaidwanderer** [comment]
Is this still happening? If so could you give me the name of the fic?

**Comment by BenGiles123** [comment]
﻿Hey Joel,

Nope it stopped at about 15:40 GMT on Saturday - I assumed you’d done something!

Thanks for the mail to check.

Ben

**Comment by waylaidwanderer** [comment]
I did restart a couple things just in case. Good to know it worked.
