### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by Walkingwalkerwalks** [waylaidwanderer/FicSave#228]
Hello, how are you? I hope you're doing well during this whole thing that's affecting the world. There's a bit of a problem  with the main site at the moment in which trying to queue up a fic to be downloaded resulted in a pop-up message 'Server Error has occurred. Please try again later.'. The good news is that the beta site is still working just fine.

**Comment by Walkingwalkerwalks** [comment]
Hello. In case you haven't read this: The main site is still unusable because of the server error.

**Comment by waylaidwanderer** [comment]
I had to reboot the server and fix some filesystem errors, but things should be working again.

What's the beta site missing so far that's stopping you from using it? I'm thinking about switching everything over once I implement the emailing feature on the beta.

Happy Easter btw!

**Comment by Walkingwalkerwalks** [comment]
Hello, firstly, thanks for fixing the issue. Secondly, as to what's really stopping me from using the beta site is that I'm more used to using the main site more than anything.

Happy Easter to you too!
