### ISSUE TITLE
Keeps saying server error

### ISSUE THREAD

**Issue by StoryGuy** [waylaidwanderer/FicSave#229]
For like the last two months or so, every time I've tried to download a fanfic, it just keeps saying "server error, try again later". After two months of this, I'm pretty sure this counts as a problem that needs fixing, so...yeah. I guess look into that whenever you can

**Comment by waylaidwanderer** [comment]
I'll look into it. Try beta.ficsave.xyz in the meantime.

**Comment by waylaidwanderer** [comment]
Fixed. Thank you
