### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by Serena006** [waylaidwanderer/FicSave#243]
For the past few days I have been unable to download fics from ff. It says Server error,  try again later. And I did but still nothing.
Pls help, ty.

**Comment by waylaidwanderer** [comment]
Hey, it looks like ffnet is blocking requests to FicSave frequently (probably due to the high number of requests from the server?).

I've updated beta.ficsave.xyz to work around this by using proxies for every request. Please give it a try.

**Comment by Walkingwalkerwalks** [comment]
Hello. First of all, the beta site works, thank you for that. Secondly, I want to tell you something that might be connected to this issue: Based on the most recent tweet from FictionPress on twitter, it seems that they've, in their words, 'experienced elevated bot attacks over the past 48 hours which have degraded the web login services'. They also wrote that 'Staff have been scrubbing the incoming traffic 24/7' and that they will 'implement more direct/indirect protection within the next 48 hours to protect access for legitimate users'. This might be why the main site doesn't work at the moment.

**Comment by waylaidwanderer** [comment]
Thanks @Walkingwalkerwalks for the info. That's likely the issue. I'll see if I can come up with some quick-fix for the main site today.

**Comment by waylaidwanderer** [comment]
The main site is now working again as well.
