### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by jeremybras** [waylaidwanderer/FicSave#245]
fanfiction.net is blocking all requests, and cloudflare seems to be the problem. Anyone has a solution ?

**Comment by waylaidwanderer** [comment]
I'll see what I can come up with.

**Comment by Walkingwalkerwalks** [comment]
Hello. Their official account on twitter says that they're doing a major migration of their network. It seems to be still ongoing at the moment and maybe that's the source of this issue. 
Update: I've read a lot of other fanfic downloaders in this site that also has issues with this. If you're interested, here's a rather long thread that discusses workarounds to this problem with varying degrees of success if you'd like to take a look: https://github.com/JimmXinu/FanFicFare/issues/614.

Also, there's a person in the above thread who suggested that it's possible that this problem might disappear on its own and I have a reason to believe them: The site itself had serious issues over the past five months, especially last month's issue where only the app version showed new and updated stories. That problem lasted for almost a week until the problem seemed to solve itself, so maybe this will end the same way too. Though with how this being something that was deliberately done, I do have a reason to doubt that it'll go away.

Lastly, from what I've read on the FictionPress twitter's recent feed, it seems that there will be another network migration for their app services that will, in their word, 'happen transparently over the next two weeks and will bring faster performance and bot mitigation.' They said that it would not disrupt too much service, but considering what happened currently, what with many users having troubles accessing the site depending on where they live, Australia and New Zealand being the ones most affected, I think you'd like to know this bit of info as well.

**Comment by Noxifer** [comment]
So... It's been a few months now ^^; Any progress on finding a solution?

**Comment by jeremybras** [comment]
Yeah... I got fed up with them, dropped my website domain + hosting, it's just not worth it anymore. All that effort

**Comment by waylaidwanderer** [comment]
Oops, forgot to close this thread. I fixed this long ago in the beta.
