### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Krysstinia** [waylaidwanderer/FicSave#246]
Hello. I'm looking for some assistance. I'm trying to download a fic from fanfiction.net and I keep getting the error message"A server error occurred, please try again later".

I get this message by putting in the URL of the fic I want, keeping the format e-pub, and clicking the download button. I've tried a couple of fics with the same result. I've used this site before with no issues. I don't understand what I'm doing wrong.

**Comment by McDouggal** [comment]
This is a known issue that the devs are working on. Short version, ff.net changed hosting providers from whatever they were on to Cloudflare, and Cloudflare's anti-bot protections are stopping the bot before it can skim the HTML to even convert it.

https://github.com/waylaidwanderer/FicSave/issues/245

**Comment by Epictyphlosion** [comment]
Update: Still isn't working

**Comment by artphilia** [comment]
I do have the same problem. :( Can't even download text files from fanfiction.net

**Comment by waylaidwanderer** [comment]
This should be fixed if you use beta.ficsave.xyz.

**Comment by artphilia** [comment]
Yes, it's working! Thanks a lot. :D
