### ISSUE TITLE
Missing chapters

### ISSUE THREAD

**Issue by swojczyszyn** [waylaidwanderer/FicSave#26]
https://www.fanfiction.net/s/8681612/

An ePub was missing chapter 10

Message instead of chapter 10

“This page contains the following errors:

error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.”

Excerpt From: Wilder, Liv. “Fertile Imagination.” FanFiction.net, 2014-06-29T00:12:09.000000+00:00. iBooks. 
This material may be protected by copyright.

**Comment by waylaidwanderer** [comment]
Should be fixed with the latest update. Thanks for the report.
