### ISSUE TITLE
API is running on HTTP and causes a server error

### ISSUE THREAD

**Issue by anurox2** [waylaidwanderer/FicSave#267]
First up I am a great fan of your work!! The website you've created is **Amazing**!!
I've been trying to download a fic for a couple of days now and it gives me the following error
![image](https://user-images.githubusercontent.com/12498263/123835564-51131600-d8ce-11eb-98cf-3d28a6673ab8.png)

It seems the API is being hit using HTTP.

**Comment by waylaidwanderer** [comment]
Ah yeah, I'm afraid that version of ficsave is no longer being maintained. If you can't use the HTTP version of the site, I would suggest using beta.ficsave.xyz instead, as all new development is happening on that branch instead.

Thanks for the donation btw!
