### ISSUE TITLE
Add story summary, characters pairing, chapters, words...

### ISSUE THREAD

**Issue by SasukeKarin** [waylaidwanderer/FicSave#38]
Should there be the story summary, characters pairing, chapters, words... at the start of the story?
![screenshot-www fanfiction net 2014-10-17 21-43-34](https://cloud.githubusercontent.com/assets/6937532/4680614/5ec26e78-560c-11e4-927d-bd41af6e3968.png)

**Comment by waylaidwanderer** [comment]
Added in the latest update.
