### ISSUE TITLE
Missing Chapters

### ISSUE THREAD

**Issue by Allayna** [waylaidwanderer/FicSave#40]
https://www.fanfiction.net/s/9142309 - chapter 19: Brodor - epub
https://www.fanfiction.net/s/2012849 - chapter 25: The Last Betrayal - epub

on iPad 2 and iPhone 4S running iOS 8, using the Marvin app
both load this error on the chapter, then it just goes to the next chapter

![2014-10-21 02 22 31](https://cloud.githubusercontent.com/assets/9332212/4714522/35326240-58f3-11e4-97a7-c015098f5a45.png)

**Comment by waylaidwanderer** [comment]
Should be fixed with the latest update. Thanks for the report.
