### ISSUE TITLE
Publication date

### ISSUE THREAD

**Issue by syrma** [waylaidwanderer/FicSave#45]
Hello, and thank you for all the effort you put into making FicSave ! 
It's no big issue, and I apologize if it was already signaled/taken care of, but the epub files I'm downloading actually come with a wrong publication date (more precisely, today's date.)
(I open them using Calibre. )
Thanks again !

**Comment by waylaidwanderer** [comment]
The publication date is by default, the time that the eBook was generated. It's unfeasible to grab the actual date reliably with so many fanfic websites, so unfortunately this can't be fixed.

**Comment by syrma** [comment]
I understand very well. Thank you for your reply !
