### ISSUE TITLE
Epub and Table of Contents

### ISSUE THREAD

**Issue by theatrophied** [waylaidwanderer/FicSave#48]
The table of contents generated with epub files is bugged. On the table of contents navigation page, the "table of contents" link appears at the end of the list even though it is at the beginning. Previously, the chapter currently being read appeared bolded on the navigation page, now it does not and the "table of contents" link is always bolded.

**Comment by waylaidwanderer** [comment]
This is due to the PHPePub library I'm using, and if there's a problem the developer needs to fix it on their end. That said, I did try to fix it myself with the latest update. Let me know if it becomes a problem again.
