### ISSUE TITLE
(fanfiction.net) download doesn't start - really long fics

### ISSUE THREAD

**Issue by LordSchmodder** [waylaidwanderer/FicSave#49]
Hey!

I just noticed that that the download doesn't start even after a long time waiting with a really long fic (over 600.000 words).
Fic in question: https://www.fanfiction.net/s/7920322/41/Mass-Effect-Human-Revolution.

And I noticed that there was an error while downloading a fic from adultfanfiction.net, that made no page breaks, instead there were chapter-long "pages".

Thank you for providing this program!

**Comment by ENDER3000** [comment]
How long did you wait? I was able to download this fic successfully:
https://www.fanfiction.net/s/5218118/1/Yet-again-with-a-little-extra-help

So it seems weird that it's not working for the one you provided. Also, what format are you trying to download?

**Comment by LordSchmodder** [comment]
I waited for hours, twice, just too see (the program showed some 20K seconds later on).
I was trying to download EPUB.

**Comment by ENDER3000** [comment]
K. Try downloading the link I posted. I'm trying to download your fic now. Both formats.

**Comment by ENDER3000** [comment]
Ok. I was able to download it as MOBI just now. Waiting a few minutes. It could be an issue with the format? Trying EPUB now

**Comment by ENDER3000** [comment]
seems to be an EPUB issue, but with this particular fanfic. I've just successfully downloaded MOBI, PDF, and Texts for your FF. But EPUB did not work. I also tried EPUB for my FF and it worked fine, and it's double the size of your fic. So it might just be an issue with that fic.

**Comment by LordSchmodder** [comment]
Funny how that works. OK. Thanks for taking a look at it.
