### ISSUE TITLE
Adult fanfiction bug with character ' " '

### ISSUE THREAD

**Issue by sarahBuisson** [waylaidwanderer/FicSave#50]
It's seem to have a bug with the character " (called guillemet in my native language) in adultFanfiction .
The text after this character is not exported.
(by exemple in this story http://hp.adult-fanfiction.org/story.php?no=600014996)

Excuse my poor english and Thank you for your app's, It's very usefull.

**Comment by waylaidwanderer** [comment]
Seems to be fixed in the latest update. Thanks for the bug report.
