### ISSUE TITLE
not downloading specific story

### ISSUE THREAD

**Issue by erinmiran** [waylaidwanderer/FicSave#52]
I just downloaded like 10 fanfics off of your site (thanks!!) but this one in particular is not downloading for some reason?

https://www.fanfiction.net/s/1962685/1/A-Stranger-in-an-Unholy-Land

I've tried it like 9 times, at this point other fics download in 5-10 seconds, but this one is still "waiting-758s"

**Comment by ENDER3000** [comment]
This is a long fic, so that could be the issue if you're trying to DL an ePub.

I got it to download a MOBI file just fine. I use this site to convert to other formats if needed

http://ebook.online-convert.com/convert-to-pdf

**Comment by waylaidwanderer** [comment]
The problem should be fixed with the latest update.
