### ISSUE TITLE
Epub format not compatible with Kindle e-mail service

### ISSUE THREAD

**Issue by GeneStarwind09** [waylaidwanderer/FicSave#54]
At least, this is what I was told by an Amazon representative. As they're just people who read things from a screen I didn't get the whole story, but the guy forwarded my query to the Kindle development department. Basically, I was wondering why all of the fanfics I send to my Kindle weren't appearing. I tried with a PDF, hey presto. So I think if this is true, epub should be greyed out when a Kindle e-mail is entered.

p.s. I put in a donation of $13.37 because I think you've done a great job with this. :wink: Go get yourself a pizza or something!

**Comment by waylaidwanderer** [comment]
Hmm, I wasn't aware of this. Can anyone else confirm? That's good to know though!

Oh and thanks for the donation, I laughed when I saw it :D

**Comment by jdpadrnos** [comment]
Can confirm.

See the [list of supported file types for email delivery](http://www.amazon.com/gp/sendtokindle/email).

**Comment by x-chadlin-x** [comment]
It dose depend on what kindle you use for the kindle paperweight dosnt support ePubs. So it might be a good Idea to check what your Kindle supports.

**Comment by waylaidwanderer** [comment]
With the newest update, I've opened email delivery to all emails, not just Kindle. I've added a warning when you hover over the Email label though. Thanks for bringing my attention to this issue!
