### ISSUE TITLE
Can't download 1 fic particualarly

### ISSUE THREAD

**Issue by ecchigo** [waylaidwanderer/FicSave#55]
Hi, I just downloaded 8 epub fics from fanfiction.net. I'm having trouble with the 9th one.https://www.fanfiction.net/s/4730390/1/Naruto-Genkyouien. I end up with a 27kb file that only contains 1 short chapter. I've read in one of the issues here saying the fic is big but the first one of the 8 I got was 616k words which isn't that much different from 693k. Any idea what's wrong? Thanks.

ecchigo

**Comment by waylaidwanderer** [comment]
This should be fixed with the latest update.
