### ISSUE TITLE
Chapters on Kindle

### ISSUE THREAD

**Issue by dag** [waylaidwanderer/FicSave#57]
On my first generation Kindle Paperwhite, sending MOBI over Whispersync (haven't tried any other methods, formats or readers), chapters are not recognized by the device, with the result that Go To only knows basic locations like Cover and End, and "Time left in chapter" is not supported (instead showing "Time left in book").

Thanks for a wonderful service!

**Comment by waylaidwanderer** [comment]
Can you test if the latest update has fixed the problem? Thanks!
