### ISSUE TITLE
Bookmarklet with Email

### ISSUE THREAD

**Issue by dag** [waylaidwanderer/FicSave#58]
If I create a bookmarklet with an email and then use it, it starts a download rather than sending the book by email, and the Email field is not prepopulated with the address I specified for the bookmarklet.  My current workaround is to edit the bookmarklet to `auto_download=no` and then manually enter my email and hit Send to Email, but it would be great if this could work automatically.

Thanks for a great service!

**Comment by waylaidwanderer** [comment]
Whoops, I didn't even notice! Thanks for fixing that.

**Comment by dag** [comment]
Thanks for fixing this, however the issue has returned, possibly following a recent downtime.  Did someone or something boot up an old revision, perhaps?

**Comment by waylaidwanderer** [comment]
You need to create a new bookmarklet, I had to change the code due to an issue with Google Adsense.
