### ISSUE TITLE
Whispersync and continually updating fics

### ISSUE THREAD

**Issue by dag** [waylaidwanderer/FicSave#60]
I read a bunch of fanfics that are in-progress.  This results in a bunch of duplicates when I use Send to Email, as I *ficsave* new chapters.  It would be great if this instead could update the existing document, rather than create another one.  I don't know if this is actually possible the way FicSave currently sends MOBI books to Kindle, but I do think it might be possible if it sent "magazines" instead of "books" (although I don't know exactly what that would entail).  Or not.  I don't fully understand "magazines" on Kindle, but maybe.

Even better, if it could watch for updates and send them automatically.  That's of course a big feature that probably takes much more coding, and I have no expectations.  Just putting the idea out there!  :-)

Thanks again for a wonderfully useful service that conveniently enables hours of reading!  If I wasn't a starving student myself I would not hesitate to donate, but alas.

**Comment by waylaidwanderer** [comment]
I don't think that would be possible. Plus watching for updates would be an unnecessary use of server resources. Thanks for the suggestion though!
