### ISSUE TITLE
Adult Fanfiction blank pages/only one chapter

### ISSUE THREAD

**Issue by ZiggyYo** [waylaidwanderer/FicSave#61]
Trying to download PDFs of these fics on adultfanfiction.net: 

http://buffy.adult-fanfiction.org/story.php?no=2056 
http://buffy.adult-fanfiction.org/story.php?no=3873

results in just Chapter 2 plus a lot of blank pages. Other file formats don't work either.

This has only happened to me once before (the blank pages, that time on fanfiction.net) with these fics:

https://www.fanfiction.net/s/467815/1/End-Game-Arc-2-Oil-Water
https://www.fanfiction.net/s/468281/1/End-Game-Arc-3-Heat

Everything else I've ever tried has downloaded smoothly and I don't know why these four don't work. They don't seem to have anything in common.

**Comment by waylaidwanderer** [comment]
This problem should be fixed in the latest update. I tested it with the first story and it works fine. Thanks for the bug report!
