### ISSUE TITLE
Download problem

### ISSUE THREAD

**Issue by felocia** [waylaidwanderer/FicSave#64]
hi, 

I only recently found ficsave and it has been a lifesaver! Thank you for developing this!!

I have downloaded a couple of fanfics from fanfiction.net and encountered problems with a series of stories by an author named drotuno: 
https://www.fanfiction.net/s/9779631/1/Gravity-Series-4-Fire-Ice - word count 159,217 words
https://www.fanfiction.net/s/7574955/1/Gravity-Series-3-Smoke-Mirrors - word count 255,360 words
https://www.fanfiction.net/s/7119225/1/Gravity-Series-2-Sin-Innocence - word count 264,549 words
https://www.fanfiction.net/s/6755101/1/Gravity-Series-1-Blood-Glory - word count 302,952 words

I prefer epub ebooks. The resulting file (epub) cannot be opend with either iBooks or the Marvin app. The error message on iBooks says the file is formatted incorrectly or is not a format that iBooks can open. The error message on marvin says the book cannot be opened because it is damages or encrypted. 

I tried different devices (iPhone 5s/ iPad 3, iOS 8.3) and different browsers ( Safari/ Dolphin/ Chrome/ Opera Coast/ Opera Mini) and the resulting file is always 353 kb or 354 kb. 

iPhone: Dolphin, Opera Coast and Chrome do not produce a file to download, just the download button changes color (dark green - light green - dark green) and counts the seconds. Only Safari and Opera Mini produces a file which cannot be opened with iBooks or Marvin, same error messages as before. 

iPad: Only Dolphin and Opera Mini produces a downloadable file which cannot be opened with either iBooks or Marvin. Same error messages as before. The other browsers is the same as on my iPhone. No file, only color changing button and counting of seconds. 

I am not sure if the problem could be with the huge word cound of story 1 to 3. However another story I downloaded was about 180k words and it was no problem to download and open it with iBooks. 

I am sorry it such a long post but I wanted to be as detailed as possible to hopefully make it easier for you to narrow down possible reasons why it is not working. 

It would be great if you still support the app.

Please look into the issue and fix it.

Thanks a lot!
V.

**Comment by waylaidwanderer** [comment]
Hi, thanks for your bug report. I appreciate the detail. The latest update should have fixed those problems; can you confirm if it works now?
