### ISSUE TITLE
Download problems in FanFiction.Net story #5890188

### ISSUE THREAD

**Issue by NunoMCSilva** [waylaidwanderer/FicSave#65]
Today I noticed the site has problems with this story:
https://www.fanfiction.net/s/5890188/1/Once-Bitten

I tested it on Firefox 37.0.2 on Linux Mint 17.1 and the results depend on chosen file format:
- For ePub, it keeps "Waiting" -- I let it go to 960 seconds before closing the tab;
- For PDF, the created file is missing the two last chapters (chapters 5 and 6 only have the titles);
- For MOBI and Text, it works.

Note: Thanks for coding this. I use the FicSave site regularly to download my favourite fanfics and read them offline.

**Comment by waylaidwanderer** [comment]
Problem has been fixed in the latest update. Thanks for using the site!
