### ISSUE TITLE
Adult Fanfiction blank pages

### ISSUE THREAD

**Issue by meikazuyr14** [waylaidwanderer/FicSave#69]
Trying to download PDFs of the fics in adultfanfiction.net which results in all of the chapters are blank pages. Other file formats don't work either.

**Comment by waylaidwanderer** [comment]
Is this still a problem after the latest update?

**Comment by meikazuyr14** [comment]
Thank you very much! 


     On Saturday, August 15, 2015 11:23 AM, Joel <notifications@github.com> wrote:
   

 Closed #69.—
