### ISSUE TITLE
Missing chapter error

### ISSUE THREAD

**Issue by Liamgrbd** [waylaidwanderer/FicSave#74]
I downloaded this fic: https://www.fanfiction.net/s/3816271/1/Inter-Nos

and found out that it missed chapter 6. I receive this error in place of the missing chapter:

“This page contains the following errors:

error on line 2 at column 1: Extra content at the end of the document
Below is a rendering of the page up to the first error.”

**Comment by waylaidwanderer** [comment]
Is this still a problem with the latest update?

**Comment by waylaidwanderer** [comment]
Just checked and it seems fine now.
