### ISSUE TITLE
Epub Text are small on phone

### ISSUE THREAD

**Issue by ukisawesome** [waylaidwanderer/FicSave#78]
After the recent update of Ficsave. I downloaded an epub file. Usually when I opened it with my reader the text would be quite big. Now the text are really small.

**Comment by ukisawesome** [comment]
Before update
![screenshot_2015-08-14-18-10-04](https://cloud.githubusercontent.com/assets/13795801/9271907/215b66ac-42b0-11e5-9e31-95ee405bd52a.png)

After update
![screenshot_2015-08-14-18-10-15](https://cloud.githubusercontent.com/assets/13795801/9271924/3cb51bfa-42b0-11e5-85f2-d8f4ab016927.png)

**Comment by waylaidwanderer** [comment]
Default font size is 12px, I think. However you should be able to change the size manually using your app.

**Comment by ukisawesome** [comment]
I tried to change the size manually but the text size didn't change.

**Comment by toseethemfly** [comment]
I have a nook tablet and this has been my issue as well. Changing the font size on the reading app does not change it at all.

**Comment by waylaidwanderer** [comment]
I just increased the font size to 18px. Is it better now, or should I make it slightly smaller?

**Comment by toseethemfly** [comment]
It is a little bit bigger now. However, unlike before the update, the font size does not change at all, and I am afraid it's still too small for me to read without straining my eyes. I am still able to change the font style though.

**Comment by waylaidwanderer** [comment]
@toseethemfly Can you test it again? I tried to fix it; let me know if it works.

**Comment by Liamgrbd** [comment]
I just downloaded one fic and there's no problem on my end: text size and font can both be changed easily on iphone iOS 8.4.

**Comment by toseethemfly** [comment]
It is working perfectly! Thank you very much for being so helpful and for this wonderful program.

**Comment by ukisawesome** [comment]
Sadly it is still small for me. It may just be the app causing the problem. If there are any apps that can be recommended that would be great.

**Comment by ukisawesome** [comment]
It's not the app.

**Comment by ukisawesome** [comment]
I take back my previous statements. The font size is fixed now.

**Comment by ukisawesome** [comment]
I take back my previous statements. The font size is fixed now.
