### ISSUE TITLE
Different allignment?

### ISSUE THREAD

**Issue by Liamgrbd** [waylaidwanderer/FicSave#79]
This is pretty subjective so please close this issue if you really don't want to change. But it'd be better to have the Title and Author to be center-alligned, while the 2 paragraphs of Summary and Metadata to be left-alligned. Currently it doesn't look good on the small view of iPhone/iPad.

It'd be nice too have the Author font to be a little bit smaller and italicized. Right now it looks too much like part of the title rather than the author's name.

**Comment by waylaidwanderer** [comment]
I've done as you suggested. Thanks.
