### ISSUE TITLE
Incomplete dates

### ISSUE THREAD

**Issue by NunoMCSilva** [waylaidwanderer/FicSave#81]
I know it's the way FanFiction.net handles dates on it's pages, but it looks weird to have "Updated: Aug 1" without the year on a file I want to keep. Can you add the year to it?

Also, what timezone do you use to show the dates? I don't know what timezone FanFiction.net is on, but I would like to know.

**Comment by waylaidwanderer** [comment]
Is the year not there for some fanfics? I grab the extra data from the fanfic summary at the top of the page, and I don't change it in any way.

**Comment by waylaidwanderer** [comment]
Anyway, there's nothing I can really do about this, sorry.

**Comment by NunoMCSilva** [comment]
The fanfics updated this year (2015) don't have the year, and the most
recent ones have something like "Uploaded: 11 min ago". Also the date is
calculated from the timestamp according to the local timezone.

To solve the year problem you would have to take to change the dates.
