### ISSUE TITLE
suggestion for preserve your server resources

### ISSUE THREAD

**Issue by sbuisson** [waylaidwanderer/FicSave#82]
Hy,
In order to limit the unwanted use of your server, you should indicate in the select list of the format what format is used by the kindle : ".mobi (kindle)" instead of  just ".mobi". 
I think a lot of people download one of the format instead of the other, and then have to redo the export in the good format.

Thank you.

**Comment by waylaidwanderer** [comment]
If you hover over the Email field, it now tells you to use MOBI format for Kindle emails.
