### ISSUE TITLE
"Create a Bookmarklet"

### ISSUE THREAD

**Issue by sue1zide** [waylaidwanderer/FicSave#85]
I'm unable to create a bookmarklet.

**Comment by waylaidwanderer** [comment]
When creating a bug report, you are expected to list the steps taken to reproduce the issue. Please explain in detail what happens when you try to create a bookmarklet, and what isn't working in the process of doing so.

**Comment by sue1zide** [comment]
This is the image I get. 

BOOKMARKLET

Create a bookmarklet to easily download fanfics! Clicking the
bookmarklet on any fanfic page will open FicSave in another window and
automatically start downloading the fanfic. 

Default Format 
▼ 

 	* ePub
 	* MOBI
 	* PDF
 	* Text

 ePub MOBI PDF Text 
 Email (optional) 
Create Bookmarklet 
Download as PDF | Ficsave 

When I click on "Download as PDF | Ficsave", nothing happens. 

On 2015-08-18 22:52, Joel wrote: 

> When creating a bug report, you are expected to list the steps taken to reproduce the issue. Please explain in detail what happens when you try to create a bookmarklet, and what isn't working in the process of doing so. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/waylaidwanderer/FicSave/issues/85#issuecomment-132427999

**Comment by waylaidwanderer** [comment]
Thanks for the detailed bug report. However, this is a non-issue since you are expected to bookmark that link (easiest way is to drag it onto your bookmarks toolbar). I will make it clearer in the future.

**Comment by sue1zide** [comment]
Thank you. It worked! 

On 2015-08-20 16:03, Joel wrote: 

> Thanks for the detailed bug report. However, this is a non-issue since you are expected to bookmark that link (easiest way is to drag it onto your bookmarks toolbar). I will make it clearer in the future. 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1]
https://github.com/waylaidwanderer/FicSave/issues/85#issuecomment-133155656
