### ISSUE TITLE
Bookmarklet with email not working since new design

### ISSUE THREAD

**Issue by dag** [waylaidwanderer/FicSave#86]
The email address seems to be base-64 encoded (perhaps intentional?) which is also what ends up in the email form field (not decoded), and when it's finished building the ebook nothing seems to happen: no email sent, no errors, no download.

Rather like the new update, though!

**Comment by x-chadlin-x** [comment]
HAve you tried deleting and creating a new one. for it did say that previous ones wouldnt work. :)

**Comment by waylaidwanderer** [comment]
Nope, that's actually my fault. Forgot to decode the email.

And yes, the base-64 encoded email is intentional, because Google Analytics tracks the URL of the webpage you're on, and they get unhappy about stuff like emails being in the URL.
