### ISSUE TITLE
cannot download Epub since the update

### ISSUE THREAD

**Issue by sachiixxx** [waylaidwanderer/FicSave#88]
I'm using a smartphone in downloading fanfic and I can't anymore since the update.

**Comment by waylaidwanderer** [comment]
I'm using a smartphone to download fanfics and I still can since the update. You're going to need to be more specific and detailed.

**Comment by sachiixxx** [comment]
Well, im trying to download via smartphone and It would load up the chapters and download pop up box would appear but thats it really, it'd say connecting. But it wont download.

**Comment by waylaidwanderer** [comment]
This seems like a phone problem. Try using a different browser. I just tried downloading a fanfic and it's working fine for me.
