### ISSUE TITLE
Downloaded ePub incomplete 

### ISSUE THREAD

**Issue by kindigo** [waylaidwanderer/FicSave#89]
https://m.fanfiction.net/s/7903626/1/Terrorism-Anarchy

The status bar reports going through all the chapters, but the finished (ePub) file contains only the table of contents.

**Comment by waylaidwanderer** [comment]
I just tried downloading that fanfic and it seems to have worked fine. All chapters are present. I also don't see anything in the logs about it. Try downloading it again and it should work.

**Comment by kindigo** [comment]
No dice-- I just tried that fic again and received the same issue. In iBooks it reports "cannot open file- formatted incorrectly or not a format iBooks can open", and in my preferred app Voice Dream, again, only the table of contents loads. 

I tried a different fic (https://m.fanfiction.net/s/5713201/1/Two-Steps-Back) and got no problems at all in either app. 

Thanks for your prompt response!!

**Comment by waylaidwanderer** [comment]
Try a different epub reader app. It opens properly on Calibre for Windows and Moon+ Reader for Android.

**Comment by bowerofbliss** [comment]
Try using the desktop version of Fanfiction.net instead of the mobile version and see if that helps. 

https://www.fanfiction.net/s/7903626/1/Terrorism-Anarchy
