### ISSUE TITLE
Bookmarklet no longer works

### ISSUE THREAD

**Issue by bowerofbliss** [waylaidwanderer/FicSave#90]
Prior to the the site revamp, I used to be able to automatically download fanfic epubs using the bookmarklet shortcut. Although the bookmarklet still works on my PC, it no longer works on my iphone or ipad, meaning that I have to copy and paste the url. Can this be rectified? Many thanks for an otherwise awesome job on the site.

**Comment by waylaidwanderer** [comment]
You need to create a new bookmarklet due to the site update.

**Comment by bowerofbliss** [comment]
I have already tried this *several times) and it did not work.

**Comment by waylaidwanderer** [comment]
Not sure how you are doing it, but this is how I do it on my phone and it works: http://www.labnol.org/software/google-chrome-bookmarklets/27894/

**Comment by bowerofbliss** [comment]
Never mind. I ended up copying the javascript function and emailing it to my iphone. I then edited the url for the saved FicSave icon on Safari on my phone, and now it works exactly as it should. When I tried to make a bookmarklet on my ipad or iphone before, I'd hit 'create' and it would come up with the message 

http://ficsave.com  - you need to bookmark this link!  

While I would try to save the link, it would only save as http://ficsave.com and did not include the javascript function required to automatically save them as epubs.
