### ISSUE TITLE
asianfanfic won't let me download the fanfic

### ISSUE THREAD

**Issue by darrensstarkid** [waylaidwanderer/FicSave#95]
i passed the url in and it said invalid link -_-

http://www.asianfanfics.com/story/view/832687/scandalous-protocol-angst-hoya-infinite-sunggyu-sungyeol-woohyun-you

that is the url

**Comment by waylaidwanderer** [comment]
18+ stories aren't working right now. I'll work on a fix for it.

**Comment by 11Rivera12** [comment]
Noooo! I wanted to read while eating dinner! XD

**Comment by waylaidwanderer** [comment]
Reading an 18+ story while eating dinner? Naughty naughty ;P

**Comment by 11Rivera12** [comment]
Ehehe, it isn't like that.. (^~^'')

**Comment by waylaidwanderer** [comment]
I've fixed this issue. Let me know if it breaks again in the future.
