### ISSUE TITLE
Fics not Downloading from FF.net

### ISSUE THREAD

**Issue by whatarefeet** [waylaidwanderer/FicSave#96]
Hi! 

This fic from FF.net is not downloading at all! 

https://www.fanfiction.net/s/2427170/1/Obsessive-Lily-Disorder

**Comment by whatarefeet** [comment]
Actually no fics are downloading =(

**Comment by waylaidwanderer** [comment]
Thanks for informing me. I've fixed the issue.

**Comment by sue1zide** [comment]
Thank you.
